### ISSUE TITLE
Use Testcontainers for integration tests

### ISSUE THREAD

**Issue by ojhughes** [albertoventurini/graphdb-intellij-plugin#30]
It might be nicer to use [Testcontainers](https://www.testcontainers.org/) for integration tests instead of embedded Neo4j. It would make testing multiple versions simpler as well

**Comment by albertoventurini** [comment]
Thank you @ojhughes, I agree with you - Testcontainers is the way to go. I was thinking about that as well. It looks like recent versions of the Neo4j test harness have issues running on Mac systems with Apple Silicon (which happens to be my system) so I haven't been able to run tests recently. It would definitely be nice to have Testcontainers to fix that.

**Comment by albertoventurini** [comment]
I had a look at this. When switching from embedded Neo4j to Testcontainers, we need to find a way to inject user functions (or a way to work around it). This is currently done here:

https://github.com/albertoventurini/graphdb-intellij-plugin/blob/main/testing/database/neo4j-4.4/src/main/java/com/albertoventurini/graphdbplugin/test/database/neo4j_4_4/Neo4j44Server.java#L22

Some tests rely on the presence of user functions in order to succeed. The first solution that comes to my mind is to compile the user function as a jar, and load the jar in the Neo4j container. However, I wonder if there might be an easier solution.

**Comment by ojhughes** [comment]
Ah I see, I think you are right that the function would need to be packaged as a plugin Jar. Could the tests use an Apoc function instead of the user defined function?

**Comment by albertoventurini** [comment]
Yes, that's the kind of workaround I was thinking as well. We should be able to replace user-defined functions with some APOC functions without changing the test semantics.

**Comment by albertoventurini** [comment]
I pushed a branch which uses Testcontainers. What's left to do is to make the tests use APOC functions instead of user-defined functions, and remove the dependency on the Neo4j test harness module.

There are a number of tests that are failing, but I suspect it might be because of other changes I made to the ebnf grammar, not related to using Testcontainers.

**Comment by albertoventurini** [comment]
@ojhughes I have a PR to use Testcontainers, if you'd like to have a look: https://github.com/albertoventurini/graphdb-intellij-plugin/pull/33

I've pulled the task of replacing user functions with APOC functions into a separate task (#32) because it doesn't really depend on Testcontainers.

**Comment by albertoventurini** [comment]
Closing as complete
